// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAcTUR3szXDS9XJy59HBH-18rrzhLFD6s',
    appId: '1:419127283736:android:73dfcc511390d4a9b2f36d',
    messagingSenderId: '419127283736',
    projectId: 'eldamn-9e018',
    storageBucket: 'eldamn-9e018.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhnfQ7NwTImeWP-6d3LxR7oNfBmjmeBDo',
    appId: '1:419127283736:ios:38a615401664ac72b2f36d',
    messagingSenderId: '419127283736',
    projectId: 'eldamn-9e018',
    storageBucket: 'eldamn-9e018.firebasestorage.app',
    iosBundleId: 'com.bayain.ehfuzdmank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhnfQ7NwTImeWP-6d3LxR7oNfBmjmeBDo',
    appId: '1:419127283736:ios:d37e00aa90a51134b2f36d',
    messagingSenderId: '419127283736',
    projectId: 'eldamn-9e018',
    storageBucket: 'eldamn-9e018.firebasestorage.app',
    iosBundleId: 'com.example.ahfazDamanak',
  );
}
